name: Terraform                               

on:
  push:                                       
    branches:                                 
      - main

jobs:
#   tflint:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - uses: terraform-linters/setup-tflint@v1
#         name: Setup TFLint
#         with:
#           tflint_version: latest

#       - name: Run TFLint
#         run: tflint -f json aws > tflint-output.json

#       - uses: actions/upload-artifact@v2
#         with:
#           name: TFLint
#           path: tflint-output.json
#         if: always()     

  terrascan:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Terrascan
        id: terrascan
        uses: accurics/terrascan-action@v1
        with:
          iac_type: 'terraform'
          iac_version: 'v14'
          policy_type: 'aws'
          only_warn: true
          iac_dir: 'aws'

  build:
    runs-on: ubuntu-20.04                    
    steps:
      - run: echo "This is a build step"

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - run: echo "This is a test step"

  integration:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-20.04
    needs: integration
    steps:
      - run: echo "This is a deploy step"
